new_to_old:
  "Chêne": "Chênes sains"
  "Chêne brogneux": "Chênes brogneux"
  "Chêne gélif": "Chênes gélifs"
  "Chêne foudroyé": "Chênes foudroyés"
  "Chêne sec": "Chênes secs"
  "Hêtre": "Hêtres sains"
  "Hêtre branchu": "Hêtres branchus"
  "Hêtre dépérissant": "Hêtres nectria"
  "Hêtre sec": "Hêtres secs"
  "Douglas": "Douglas"
  "Douglas branchu": "Douglas branchus"
  "Douglas nécrosé": "Douglas nécrosés"
  "Douglas sec": "Douglas secs"
  "Epicéa commun": "Epicéas communs"
  "Epicéa commun dépérissant": "Epicéas secs"
  "Epicéa commun sec": "Epicéas secs"
  "Epicéa de Sitka": "Epicéas de Sitka"
  "Epicéa de Sitka dépérissant": "Epicéas de Sitka"
  "Epicéa de Sitka sec": "Epicéas de Sitka"
  "Sapin pectiné": "Sapins pectinés"
  "Sapin pectiné dépérissant": "Sapins pectinés"
  "Sapin pectiné sec": "Sapins pectinés"
  "Alisier blanc": "Alisiers blancs"
  "Alisier torminal": "Alisiers torminaux"
  "Aulne glutineux": "Aulnes glutineux"
  "Bouleau": "Bouleaux"
  "Charme": "Charmes BO"
  "Châtaignier": "Châtaigniers"
  "Chêne chevelu": "Chênes chevelus"
  "Chêne des marais": "Chênes des marais"
  "Chêne liège": "Chênes liège"
  "Chêne pubescent": "Chênes pubescents"
  "Chêne rouge d'Amérique": "Chênes rouges d'Amérique"
  "Chêne tauzin": "Chênes tauzin"
  "Chêne vert": "Chênes verts"
  "Cormier": "Cormiers"
  "Erable champêtre": "Erables champêtres"
  "Erable plane": "Erables planes"
  "Erable sycomore": "Erables sycomores"
  "Eucaplyptus": "Eucaplyptus"
  "Frêne": "Frênes"
  "Fruitier": "Fruitiers"
  "Marronnier": "Marroniers"
  "Merisier": "Merisiers"
  "Noisetier": "Divers feuillus"
  "Noyer commun": "Noyers communs"
  "Noyer hybride": "Noyers hybrides"
  "Noyer noir": "Noyers noirs"
  "Orme": "Ormes"
  "Peuplier clonal": "Peupliers clonaux"
  "Peuplier naturel": "Peupliers naturels"
  "Robinier": "Robiniers"
  "Saule": "Divers feuillus"
  "Tilleul": "Tilleuls"
  "Tremble": "Trembles"
  "Tulipier de Virginie": "Tulipiers de Virginie"
  "Cèdre": "Cèdres"
  "Crytoméria": "Crytomérias"
  "Cyprès": "Cyprès"
  "Mélèze": "Mélèzes"
  "Métaséquoia": "Métaséquoias"
  "Pin à crochets": "Pins à crochets"
  "Pin à l'encens (taeda)": "Pins à l'encens (taeda)"
  "Pin brutia": "Pins brutia"
  "Pin cembro": "Pins cembro"
  "Pin d'Alep": "Pins d'Alep"
  "Pin de Monterey": "Pins de Monterey"
  "Pin de Salzmann": "Pins de Salzmann"
  "Pin laricio": "Pins laricios"
  "Pin maritime": "Pins maritimes"
  "Pin noir d'Autriche": "Pins noirs d'Autriche"
  "Pin sylvestre": "Pins sylvestres"
  "Pin Weymouth": "Pins Weymouth"
  "Sapin de Vancouver": "Sapins de Vancouver"
  "Sapin du Caucase (Nordmann)": "Sapins du Caucase (Nordmann)"
  "Séquoia géant": "Séquoia géant"
  "Séquoia toujours vert": "Séquoia toujours vert"
  "Thuya": "Thuyas"
  "Tsuga hétérophylle": "Tsugahétérophylle"
  "Trituration feuillue": "Divers feuillus"
  "Trituration résineuse": "Bois secs résineux"
  "Divers feuillus": "Divers feuillus"
  "Divers résineux": "Divers résineux"
  "Sapin de Turquie (Bornmuller)": "Divers résineux"
  "Houx": "Divers résineux"


