# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Qsequoia2
                                 A QGIS plugin
 Plugin to create forest GIS project
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-13
        copyright            : (C) 2025 by Matthieu CHEVEREAU
        email                : matthieu.chevereau@hotmail.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Qsequoia2 class from file Sequoia2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Qsequoia2 import Qsequoia2
    return Qsequoia2(iface)
