# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDataDialog(object):
    def setupUi(self, AddDataDialog):
        AddDataDialog.setObjectName("AddDataDialog")
        AddDataDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddDataDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.checkBox_4 = QtWidgets.QCheckBox(AddDataDialog)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 130, 321, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_3 = QtWidgets.QCheckBox(AddDataDialog)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 100, 321, 17))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_1 = QtWidgets.QCheckBox(AddDataDialog)
        self.checkBox_1.setGeometry(QtCore.QRect(20, 40, 321, 17))
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(AddDataDialog)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 70, 321, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_layers = QtWidgets.QLabel(AddDataDialog)
        self.label_layers.setGeometry(QtCore.QRect(20, 10, 191, 16))
        self.label_layers.setObjectName("label_layers")
        self.checkBox_5 = QtWidgets.QCheckBox(AddDataDialog)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 160, 321, 17))
        self.checkBox_5.setObjectName("checkBox_5")

        self.retranslateUi(AddDataDialog)
        self.buttonBox.accepted.connect(AddDataDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AddDataDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddDataDialog)

    def retranslateUi(self, AddDataDialog):
        _translate = QtCore.QCoreApplication.translate
        AddDataDialog.setWindowTitle(_translate("AddDataDialog", "Ajouter de couches"))
        self.checkBox_4.setText(_translate("AddDataDialog", "MNH"))
        self.checkBox_3.setText(_translate("AddDataDialog", "TOPO_line"))
        self.checkBox_1.setText(_translate("AddDataDialog", "ROUTE_line + ROUTE_polygon"))
        self.checkBox_2.setText(_translate("AddDataDialog", "PF_line + PF_polygon + SSPF_polygon + UA_polygon"))
        self.label_layers.setText(_translate("AddDataDialog", "Couches à ajouter"))
        self.checkBox_5.setText(_translate("AddDataDialog", "MNT"))
