# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diagnostic.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiagnosticDialog(object):
    def setupUi(self, DiagnosticDialog):
        DiagnosticDialog.setObjectName("DiagnosticDialog")
        DiagnosticDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(DiagnosticDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(DiagnosticDialog)
        self.buttonBox.accepted.connect(DiagnosticDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DiagnosticDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DiagnosticDialog)

    def retranslateUi(self, DiagnosticDialog):
        _translate = QtCore.QCoreApplication.translate
        DiagnosticDialog.setWindowTitle(_translate("DiagnosticDialog", "Création de diagnostic"))
