# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'global_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GlobalSettingsDialog(object):
    def setupUi(self, GlobalSettingsDialog):
        GlobalSettingsDialog.setObjectName("GlobalSettingsDialog")
        GlobalSettingsDialog.resize(400, 180)
        self.buttonBox = QtWidgets.QDialogButtonBox(GlobalSettingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 130, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_agence = QtWidgets.QLabel(GlobalSettingsDialog)
        self.label_agence.setGeometry(QtCore.QRect(10, 10, 151, 20))
        self.label_agence.setObjectName("label_agence")
        self.combobox_agence = QtWidgets.QComboBox(GlobalSettingsDialog)
        self.combobox_agence.setGeometry(QtCore.QRect(180, 10, 171, 22))
        self.combobox_agence.setObjectName("combobox_agence")
        self.userInput = QtWidgets.QLineEdit(GlobalSettingsDialog)
        self.userInput.setGeometry(QtCore.QRect(180, 100, 171, 20))
        self.userInput.setObjectName("userInput")
        self.label_user = QtWidgets.QLabel(GlobalSettingsDialog)
        self.label_user.setGeometry(QtCore.QRect(10, 100, 151, 16))
        self.label_user.setObjectName("label_user")
        self.label_style = QtWidgets.QLabel(GlobalSettingsDialog)
        self.label_style.setGeometry(QtCore.QRect(10, 40, 151, 16))
        self.label_style.setObjectName("label_style")
        self.stylesInput = QtWidgets.QLineEdit(GlobalSettingsDialog)
        self.stylesInput.setGeometry(QtCore.QRect(180, 40, 171, 20))
        self.stylesInput.setObjectName("stylesInput")
        self.modelsInput = QtWidgets.QLineEdit(GlobalSettingsDialog)
        self.modelsInput.setGeometry(QtCore.QRect(180, 70, 171, 20))
        self.modelsInput.setObjectName("modelsInput")
        self.label_models = QtWidgets.QLabel(GlobalSettingsDialog)
        self.label_models.setGeometry(QtCore.QRect(10, 70, 151, 16))
        self.label_models.setObjectName("label_models")
        self.stylesButton = QtWidgets.QPushButton(GlobalSettingsDialog)
        self.stylesButton.setGeometry(QtCore.QRect(360, 40, 31, 21))
        self.stylesButton.setObjectName("stylesButton")
        self.modelsButton = QtWidgets.QPushButton(GlobalSettingsDialog)
        self.modelsButton.setGeometry(QtCore.QRect(360, 70, 31, 21))
        self.modelsButton.setObjectName("modelsButton")

        self.retranslateUi(GlobalSettingsDialog)
        self.buttonBox.accepted.connect(GlobalSettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(GlobalSettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(GlobalSettingsDialog)

    def retranslateUi(self, GlobalSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        GlobalSettingsDialog.setWindowTitle(_translate("GlobalSettingsDialog", "Paramétrage général"))
        self.label_agence.setText(_translate("GlobalSettingsDialog", "Agence"))
        self.label_user.setText(_translate("GlobalSettingsDialog", "Utilisateur"))
        self.label_style.setText(_translate("GlobalSettingsDialog", "Bibliothèque de styles"))
        self.label_models.setText(_translate("GlobalSettingsDialog", "Bibliothèque de modèles"))
        self.stylesButton.setText(_translate("GlobalSettingsDialog", "..."))
        self.modelsButton.setText(_translate("GlobalSettingsDialog", "..."))
