# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'global_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GlobalSettingsDialog(object):
    def setupUi(self, GlobalSettingsDialog):
        GlobalSettingsDialog.setObjectName("GlobalSettingsDialog")
        GlobalSettingsDialog.resize(400, 129)
        self.buttonBox = QtWidgets.QDialogButtonBox(GlobalSettingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 80, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_agence = QtWidgets.QLabel(GlobalSettingsDialog)
        self.label_agence.setGeometry(QtCore.QRect(10, 10, 141, 20))
        self.label_agence.setObjectName("label_agence")
        self.combobox_agence = QtWidgets.QComboBox(GlobalSettingsDialog)
        self.combobox_agence.setGeometry(QtCore.QRect(180, 10, 151, 22))
        self.combobox_agence.setObjectName("combobox_agence")
        self.userInput = QtWidgets.QLineEdit(GlobalSettingsDialog)
        self.userInput.setGeometry(QtCore.QRect(180, 40, 171, 20))
        self.userInput.setObjectName("userInput")
        self.label_user = QtWidgets.QLabel(GlobalSettingsDialog)
        self.label_user.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.label_user.setObjectName("label_user")

        self.retranslateUi(GlobalSettingsDialog)
        self.buttonBox.accepted.connect(GlobalSettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(GlobalSettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(GlobalSettingsDialog)

    def retranslateUi(self, GlobalSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        GlobalSettingsDialog.setWindowTitle(_translate("GlobalSettingsDialog", "Paramétrage général"))
        self.label_agence.setText(_translate("GlobalSettingsDialog", "Agence"))
        self.label_user.setText(_translate("GlobalSettingsDialog", "Utilisateur"))
