# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pedology.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PedologyDialog(object):
    def setupUi(self, PedologyDialog):
        PedologyDialog.setObjectName("PedologyDialog")
        PedologyDialog.resize(404, 132)
        self.buttonBox = QtWidgets.QDialogButtonBox(PedologyDialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 80, 361, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(PedologyDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 361, 16))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(PedologyDialog)
        self.comboBox.setGeometry(QtCore.QRect(20, 40, 351, 22))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(PedologyDialog)
        self.buttonBox.rejected.connect(PedologyDialog.reject) # type: ignore
        self.buttonBox.accepted.connect(PedologyDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PedologyDialog)

    def retranslateUi(self, PedologyDialog):
        _translate = QtCore.QCoreApplication.translate
        PedologyDialog.setWindowTitle(_translate("PedologyDialog", "Création de Pedologie"))
        self.label.setText(_translate("PedologyDialog", "Guide de station :"))
