# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\OSGeo4W\apps\qgis-ltr\python\plugins\Qsequoia2\dialogs\pedology.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PedologyDialog(object):
    def setupUi(self, PedologyDialog):
        PedologyDialog.setObjectName("PedologyDialog")
        PedologyDialog.resize(532, 292)
        self.buttonBox = QtWidgets.QDialogButtonBox(PedologyDialog)
        self.buttonBox.setGeometry(QtCore.QRect(160, 250, 361, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gb_global_param = QtWidgets.QGroupBox(PedologyDialog)
        self.gb_global_param.setGeometry(QtCore.QRect(10, 10, 511, 161))
        self.gb_global_param.setObjectName("gb_global_param")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.gb_global_param)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 60, 491, 91))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_layers_11 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_layers_11.setObjectName("label_layers_11")
        self.gridLayout_4.addWidget(self.label_layers_11, 1, 0, 1, 1)
        self.le_package_title = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.le_package_title.setEnabled(True)
        self.le_package_title.setReadOnly(False)
        self.le_package_title.setPlaceholderText("")
        self.le_package_title.setObjectName("le_package_title")
        self.le_package_title.setPlaceholderText("Default to : FORET_pedology")
        self.gridLayout_4.addWidget(self.le_package_title, 1, 1, 1, 1)
        self.cb_package_for_qfield = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.cb_package_for_qfield.setToolTip("")
        self.cb_package_for_qfield.setStatusTip("")
        self.cb_package_for_qfield.setChecked(True)
        self.cb_package_for_qfield.setObjectName("cb_package_for_qfield")
        self.gridLayout_4.addWidget(self.cb_package_for_qfield, 0, 0, 1, 1)
        self.label_layers_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_layers_12.setObjectName("label_layers_12")
        self.gridLayout_4.addWidget(self.label_layers_12, 2, 0, 1, 1)
        self.fw_package_outdir = QgsFileWidget(self.gridLayoutWidget_4)
        self.fw_package_outdir.setToolTip("")
        self.fw_package_outdir.setOptions(QtWidgets.QFileDialog.ShowDirsOnly)
        self.fw_package_outdir.setObjectName("fw_package_outdir")
        self.gridLayout_4.addWidget(self.fw_package_outdir, 2, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.gb_global_param)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 491, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_layers_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_layers_4.setObjectName("label_layers_4")
        self.horizontalLayout.addWidget(self.label_layers_4)
        self.le_forest_name = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.le_forest_name.setEnabled(False)
        self.le_forest_name.setObjectName("le_forest_name")
        self.horizontalLayout.addWidget(self.le_forest_name)
        self.groupBox = QtWidgets.QGroupBox(PedologyDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 180, 511, 61))
        self.groupBox.setObjectName("groupBox")
        self.cob_stations = QtWidgets.QComboBox(self.groupBox)
        self.cob_stations.setGeometry(QtCore.QRect(10, 30, 491, 21))
        self.cob_stations.setObjectName("cob_stations")

        self.retranslateUi(PedologyDialog)
        self.buttonBox.rejected.connect(PedologyDialog.reject) # type: ignore
        self.buttonBox.accepted.connect(PedologyDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PedologyDialog)

    def retranslateUi(self, PedologyDialog):
        _translate = QtCore.QCoreApplication.translate
        PedologyDialog.setWindowTitle(_translate("PedologyDialog", "Création de Pedologie"))
        self.gb_global_param.setTitle(_translate("PedologyDialog", "Paramétrage Généraux"))
        self.label_layers_11.setText(_translate("PedologyDialog", "Nom du paquet :"))
        self.cb_package_for_qfield.setText(_translate("PedologyDialog", "Paquet pour Qfield"))
        self.label_layers_12.setText(_translate("PedologyDialog", "Répertoire de sortie :"))
        self.label_layers_4.setText(_translate("PedologyDialog", "Forêt :"))
        self.groupBox.setTitle(_translate("PedologyDialog", "Guide de station"))
from qgsfilewidget import QgsFileWidget
