# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectSettingsDialog(object):
    def setupUi(self, ProjectSettingsDialog):
        ProjectSettingsDialog.setObjectName("ProjectSettingsDialog")
        ProjectSettingsDialog.resize(400, 148)
        self.buttonBox = QtWidgets.QDialogButtonBox(ProjectSettingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 100, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_repertoire = QtWidgets.QLabel(ProjectSettingsDialog)
        self.label_repertoire.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_repertoire.setObjectName("label_repertoire")
        self.lineEdit_repertoire = QtWidgets.QLineEdit(ProjectSettingsDialog)
        self.lineEdit_repertoire.setGeometry(QtCore.QRect(176, 10, 171, 20))
        self.lineEdit_repertoire.setAcceptDrops(True)
        self.lineEdit_repertoire.setObjectName("lineEdit_repertoire")
        self.lineEdit_prefixe = QtWidgets.QLineEdit(ProjectSettingsDialog)
        self.lineEdit_prefixe.setGeometry(QtCore.QRect(176, 40, 171, 20))
        self.lineEdit_prefixe.setObjectName("lineEdit_prefixe")
        self.label_prefixe = QtWidgets.QLabel(ProjectSettingsDialog)
        self.label_prefixe.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.label_prefixe.setObjectName("label_prefixe")
        self.pushButton = QtWidgets.QPushButton(ProjectSettingsDialog)
        self.pushButton.setGeometry(QtCore.QRect(360, 10, 31, 21))
        self.pushButton.setObjectName("pushButton")
        self.label_project = QtWidgets.QLabel(ProjectSettingsDialog)
        self.label_project.setGeometry(QtCore.QRect(10, 70, 181, 20))
        self.label_project.setObjectName("label_project")
        self.comboBox_projects = QtWidgets.QComboBox(ProjectSettingsDialog)
        self.comboBox_projects.setGeometry(QtCore.QRect(200, 70, 151, 22))
        self.comboBox_projects.setObjectName("comboBox_projects")

        self.retranslateUi(ProjectSettingsDialog)
        self.buttonBox.accepted.connect(ProjectSettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ProjectSettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ProjectSettingsDialog)

    def retranslateUi(self, ProjectSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        ProjectSettingsDialog.setWindowTitle(_translate("ProjectSettingsDialog", "Création de projet"))
        self.label_repertoire.setText(_translate("ProjectSettingsDialog", "Répertoire de travail"))
        self.label_prefixe.setText(_translate("ProjectSettingsDialog", "Préfixe de la forêt"))
        self.pushButton.setText(_translate("ProjectSettingsDialog", "..."))
        self.label_project.setText(_translate("ProjectSettingsDialog", "Sélectionner le projet de carte"))
