# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectSettingsDialog(object):
    def setupUi(self, ProjectSettingsDialog):
        ProjectSettingsDialog.setObjectName("ProjectSettingsDialog")
        ProjectSettingsDialog.setEnabled(True)
        ProjectSettingsDialog.resize(535, 100)
        self.buttonBox = QtWidgets.QDialogButtonBox(ProjectSettingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 60, 511, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.checkBox_saved = QtWidgets.QCheckBox(ProjectSettingsDialog)
        self.checkBox_saved.setGeometry(QtCore.QRect(20, 60, 341, 20))
        self.checkBox_saved.setObjectName("checkBox_saved")
        self.label_project = QtWidgets.QLabel(ProjectSettingsDialog)
        self.label_project.setGeometry(QtCore.QRect(20, 20, 181, 20))
        self.label_project.setObjectName("label_project")
        self.comboBox_projects = QtWidgets.QComboBox(ProjectSettingsDialog)
        self.comboBox_projects.setGeometry(QtCore.QRect(190, 20, 151, 22))
        self.comboBox_projects.setObjectName("comboBox_projects")

        self.retranslateUi(ProjectSettingsDialog)
        self.buttonBox.accepted.connect(ProjectSettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ProjectSettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ProjectSettingsDialog)

    def retranslateUi(self, ProjectSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        ProjectSettingsDialog.setWindowTitle(_translate("ProjectSettingsDialog", "Création de projet"))
        self.checkBox_saved.setText(_translate("ProjectSettingsDialog", "Enregistrer automatiquement après création"))
        self.label_project.setText(_translate("ProjectSettingsDialog", "Sélectionner le projet de carte :"))
