# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\OSGeo4W\apps\qgis-ltr\python\plugins\Qsequoia2\dialogs\project_settings\project_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectSettingsDialog(object):
    def setupUi(self, ProjectSettingsDialog):
        ProjectSettingsDialog.setObjectName("ProjectSettingsDialog")
        ProjectSettingsDialog.setEnabled(True)
        ProjectSettingsDialog.resize(395, 143)
        self.verticalLayoutWidget = QtWidgets.QWidget(ProjectSettingsDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_project = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_project.setObjectName("label_project")
        self.horizontalLayout.addWidget(self.label_project)
        self.comboBox_projects = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_projects.sizePolicy().hasHeightForWidth())
        self.comboBox_projects.setSizePolicy(sizePolicy)
        self.comboBox_projects.setObjectName("comboBox_projects")
        self.horizontalLayout.addWidget(self.comboBox_projects)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.cb_save_project = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_save_project.setObjectName("cb_save_project")
        self.verticalLayout.addWidget(self.cb_save_project)
        self.cb_composeur = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.cb_composeur.setObjectName("cb_composeur")
        self.verticalLayout.addWidget(self.cb_composeur)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ProjectSettingsDialog)
        self.buttonBox.accepted.connect(ProjectSettingsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ProjectSettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ProjectSettingsDialog)

    def retranslateUi(self, ProjectSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        ProjectSettingsDialog.setWindowTitle(_translate("ProjectSettingsDialog", "Création de projet"))
        self.label_project.setText(_translate("ProjectSettingsDialog", "Sélectionner un projet :"))
        self.cb_save_project.setText(_translate("ProjectSettingsDialog", "Enregistrer automatiquement après création"))
        self.cb_composeur.setText(_translate("ProjectSettingsDialog", "Ouvrir le composeur"))
