agences:
  Boulogne:
    nom: "Racines"
    adresse: "28 bis, rue Vauthier - 92 100 Boulogne-Billancourt"
    numero: "+33 1 41 03 20 33"
    mail: "cabinet@racines.com"
    site: "www.racines.com"
  Nancy:
    nom: "Racines"
    adresse: "23, rue Saint Dizier – 54 000 Nancy"
    numero: "+33 3 54 00 16 47"
    mail: "cabinet@racines.com"
    site: "www.racines.com"
  Chaumont:
    nom: "Racines"
    adresse: "5, rue du Château – 52 000 Chamarandes"
    numero: "+33 3 25 03 16 97"
    mail: "cabinet@racines.com"
    site: "www.racines.com"
  "Le Mans":
    nom: "Racines"
    adresse: "29, rue des Marais Bât C – 72 000 Le Mans"
    numero: "+33 2 43 42 82 67"
    mail: "cabinet@racines.com"
    site: "www.racines.com"
  Alluy:
    nom: "Racines"
    adresse: "310, rue des Heurtras – 58 110 Alluy"
    numero: "+33 6 08 71 08 51"
    mail: "cabinet@racines.com"
    site: "www.racines.com"
