limites:
  LPL:
    label: "Limite de peuplement"
    color: "gold"
    width: 0.8
    style: dashdot
  MEM:
    label: "Même peuplement"
    color: "steelblue"
    width: 1
    style: solid
  LPF:
    label: "Limite de parcelle"
    color: "limegreen"
    width: 0.8
    style: dash
  RFO:
    label: "Route"
    color: "red"
    width: 0.8
    style: solid
  PNA:
    label: "Piste"
    color: "magenta"
    width: 0.6
    style: dot
  RUI:
    label: "Ruisseau/Fossé"
    color: "cyan"
    width: 0.8
    style: dashdot
  TAL:
    label: "Talus"
    color: "peru"
    width: 0.8
    style: solid
  CLO:
    label: "Clôture"
    color: "black"
    width: 0.8
    style: dash
  OTH:
    label: "Autre"
    color: "gray"
    width: 0.8
    style: dashdotdot
