
proj:
  path: "0_projet/"
  files:
    enjeux:
      env:      { filename: "ENJEUX_ENVIRONNEMENTAUX.qgz", label: "Enjeux environnementaux" }
      pat:      { filename: "ENJEUX_PATRIMONIAUX.qgz",     label: "Enjeux patrimoniaux"     }
      soc:      { filename: "ENJEUX_SOCIAUX.qgz",          label: "Enjeux sociaux"          }
    ame:        { filename: "AMENAGEMENTS.qgz",            label: "Aménagements"            }
    assemblage: { filename: "ASSEMBLAGE.qgz",              label: "Assemblage"              }
    geol:       { filename: "GEOLOGIE.qgz",                label: "Géologie"                }
    pedo:       { filename: "PEDOLOGIE.qgz",               label: "Pédologie"               }
    plt:        { filename: "PEUPLEMENT.qgz",              label: "Peuplement"              }
    situation:  { filename: "SITUATION.qgz",               label: "Situation"               }

terrain:
  path: "1_terrain/"
  files:
    exp:
      gpkg:     { filename: expertise.gpkg,    style: ~  }
      xlsx:     { filename: expertise.xlsx,    style: ~  }
    inv:
      gpkg:     { filename: inventaire.gpkg,   style: ~  }
      xlsx:     { filename: inventaire.xlsx,   style: ~  }
    pedo:
      gpkg:     { filename: pedologie.gpkg,    style: ~            }
      xlsx:     { filename: pedologie.xlsx,    style: ~            }
      sondage:  { filename: ~,                 style: sondage.qml  }
      horizons: { filename: ~,                 style: horizons.qml }
    diag:
      gpkg:     { filename: diagnostique.gpkg, style: ~            }
      xlsx:     { filename: diagnostique.xlsx, style: ~            }
      pla:      { filename: ~,                 style: Placette.qml }
      tra:      { filename: ~,                 style: Transect.qml }
      limite:   { filename: ~,                 style: Limite.qml   }
      picto:    { filename: ~,                 style: Picto.qml    }
      gha:      { filename: ~,                 style: Gha.qml      }
      tse:      { filename: ~,                 style: Tse.qml      }
      reg:      { filename: ~,                 style: Reg.qml      }
      va_ess:   { filename: ~,                 style: Va_ess.qml   }
      ess:      { filename: ~,                 style: Ess.qml      }  

rast:
  path: "2_sequoia/raster/"
  files:
    mns:       { filename: "MNS.tif",     label: Modèle Numérique de Surface,      style: ~            }
    mnt:       { filename: "MNT.tif",     label: Modèle Numérique de Terrain,      style: ~            }
    mnh:       { filename: "MNH.tif",     label: Modèle Numérique de Hauteur,      style: "MNH.qml"    }
    plt:       { filename: "PLT.tif",     label: "Carte des Peuplements",          style: ~            }
    plt_anc:   { filename: "PLT_ANC.tif", label: "Carte des Peuplements Ancienne", style: ~            }
    irc:       { filename: "IRC.tif",     label: "BD ORTHO - Infra-rouge couleur", style: ~            }
    rgb:       { filename: "RGB.tif",     label: "BD ORTHO - Couleur",             style: ~            }
    scan25:    { filename: "SCAN25.tif",  label: "Scan 25",                        style: "SCAN25.qml" }

vect:
  path: "2_sequoia/vecteur/"
  files:
    ame:
      poly:    { filename: AME_polygon.shp,           label: ~,                        style: ~                          }
    bati:
      poly:    { filename: BATICA_polygon.shp,        label: ~,                        style: ~                          }
    com:
      point:   { filename: COM_point.shp,             label: "Centre de Commune",      style: COMS_point.qml             }
      line:    { filename: COM_line.shp,              label: "Limite de Commune",      style: COMS_line.qml              }
    coms:
      point:   { filename: COMS_point.shp,            label: "Centres des Communes" ,  style: COMS_point.qml             }
      line:    { filename: COMS_line.shp,             label: "Limites des Communes" ,  style: COMS_line.qml              }
      poly:    { filename: COMS_polygon.shp,          label: "Communes"                                                  }
    geol:
      poly:    { filename: GEOL_polygon.shp,          label: "Géologie",               style: GEOL_polygon.qml           }
    infra:
      point:   { filename: INFRA_point.shp,           label: ~,                        style: INFRA_point.qml            }
      line:    { filename: INFRA_line.shp,            label: ~,                        style: INFRA_line.qml             }
      poly:    { filename: INFRA_polygon.shp,         label: ~,                        style: INFRA_polygon.qml          }
      acces:   { filename: INFRA_point.shp,           label: ~,                        style: INFRA_point_ACCES.qml      }
    lieudit:
      point:   { filename: LIEUDIT_point.shp,         label: "Lieu-dit",               style: LIEUDIT_point.qml          }  
    parca:
      poly:    { filename: PARCA_polygon.shp,         label: "Parcelle cadastrale",    style: PARCA_polygon.qml          }
      occup:   { filename: PARCA_polygon.shp,         label: "Parcelle cadastrale *",  style: PARCA_polygon_OCCUP.qml    }
      legend:  { filename: PARCA_polygon.shp,         label: "Légende",                style: INFRASTRUCTURE_polygon.qml }
      archive: { filename: PARCA-ARCHIVE_polygon.shp, label: "Parcha archive",         style: ~                          }
    pf:
      line:    { filename: PF_line.shp,               label: "Limite de parcelle",     style: PF_line.qml                }
      poly:    { filename: PF_polygon.shp,            label: "Parcelle",               style: PF_polygon.qml             }
      white:   { filename: PROP_line.shp,             label: "Limite de parcelle w",   style: PF-Diag_line.qml           }
    sspf: 
      poly:    { filename: SSPF_polygon.shp,          label: "Sous-parcelle",          style: SSPF_polygon.qml           }
      white:    { filename: SSPF_polygon.shp,         label: "Sous-parcelle w",        style: SSPF-Diag_polygon.qml      }
      plt:     { filename: SSPF_polygon.shp,          label: "Peuplements (SSPF)",     style: SSPF2_polygon.qml          }
      inv:     { filename: SSPFinv_polygon.shp,       label: ~,                        style: ~                          }
    prop:
      point:   { filename: PROP_point.shp,            label: "Centroid de propriété",  style: PROP_point.qml             }
      line:    { filename: PROP_line.shp,             label: "Limite de propriété",    style: PROP_line.qml              }
      poly:    { filename: PROP_polygon.shp,          label : Propriété,               style: PROP_polygon.qml           }
      white:    { filename: PROP_line.shp,            label: "Limite de propriété w",  style: PROP-Diag_line.qml         }
    route:
      line:    { filename: ROUTE_line.shp,            label: "Routes",                 style: ROUTE_line.qml             }
      poly:    { filename: ROUTE_polygon.shp,         label: "Routes",                 style: ROUTE_polygon.qml          }
    topo:
      line:    { filename: TOPO_line.shp,             label: "Topologie",              style: TOPO_line.qml              }
    ua:
      poly:    { filename: UA_polygon.shp,            label: "Unité d analyse",        style: UA_polygon.qml             }
      ame:     { filename: UA_polygon.shp,            label: "Aménagements (UA)",      style: UA2_polygon.qml            }
      occup:   { filename: UA_polygon.shp,            label: "Occupation du sol",      style: UA3_polygon.qml            }
      plt:     { filename: UA_polygon.shp,            label: "Peuplements (UA)",       style: UA2_polygon.qml            }
    znieff1:
      poly:    { filename: ZNIEFF1_polygon.shp,       label: ~,                        style: ~                          }
    znieff2:
      poly:    { filename: ZNIEFF2_polygon.shp,       label: ~,                        style: ~                          }

autre:
  path: "3_autre/"

res:
  path: "4_resultat/"