old_to_new_ess:
    "Chênes": "Chêne"
    "Chênes sains": "Chêne"
    "Chênes brogneux": "Chêne brogneux"
    "Chênes merrain": "Chêne"
    "Chênes gélifs": "Chêne gélif"
    "Chênes foudroyés": "Chêne foudroyé"
    "Chênes secs": "Chêne sec"
    "Chênes chauffages": "Chêne sec"
    "Chênes tarés": "Chêne brogneux"
    "Chênes chevelus": "Chêne chevelu"
    "Chênes des marais": "Chêne des marais"
    "Chênes liège": "Chêne liège"
    "Chênes pubescents": "Chêne pubescent"
    "Chênes rouges d'Amérique": "Chêne rouge d'Amérique"
    "Chênes tauzin": "Chêne tauzin"
    "Chênes verts": "Chêne vert"
    "Hêtres": "Hêtre"
    "Hêtres sains": "Hêtre"
    "Hêtres branchus": "Hêtre branchu"
    "Hêtres nectria": "Hêtre dépérissant"
    "Hêtres secs": "Hêtre sec"
    "Châtaigniers": "Châtaignier"
    "Erables planes": "Erable plane"
    "Erables sycomores": "Erable sycomore"
    "Frênes": "Frêne"
    "Tulipiers de Virginie": "Tulipier de Virginie"
    "Peupliers naturels": "Peuplier naturel"
    "Peupliers clonaux": "Peuplier clonal"
    "Robiniers": "Robinier"
    "Eucaplyptus": "Eucaplyptus"
    "Alisiers torminaux": "Alisier torminal"
    "Alisiers blancs": "Alisier blanc"
    "Cormiers": "Cormier"
    "Merisiers": "Merisier"
    "Fruitiers": "Fruitier"
    "Ormes": "Orme"
    "Marroniers": "Marronnier"
    "Noyers communs": "Noyer commun"
    "Noyers noirs": "Noyer noir"
    "Noyers hybrides": "Noyer hybride"
    "Aulnes glutineux": "Aulne glutineux"
    "Bouleaux": "Bouleau"
    "Charmes BO": "Charme"
    "Charmes BI": "Trituration feuillue"
    "Erables champêtres": "Erable champêtre"
    "Tilleuls": "Tilleul"
    "Trembles": "Tremble"
    "Douglas": "Douglas"
    "Douglas branchus": "Douglas branchu"
    "Douglas nécrosés": "Douglas nécrosé"
    "Douglas secs": "Douglas sec"
    "Mélèzes": "Mélèze"
    "Cèdres": "Cèdre"
    "Epicéas communs": "Epicéa commun"
    "Epicéas de Sitka": "Epicéa de Sitka"
    "Epicéas scoltytés frais": "Epicéa commun"
    "Epicéas secs": "Epicéa commun sec"
    "Pins à crochets": "Pin à crochets"
    "Pins brutia": "Pin brutia"
    "Pins cembro": "Pin cembro"
    "Pins d'Alep": "Pin d'Alep"
    "Pins de Monterey": "Pin de Monterey"
    "Pins de Salzmann": "Pin de Salzmann"
    "Pins maritimes": "Pin maritime"
    "Pins sylvestres": "Pin sylvestre"
    "Pins laricios": "Pin laricio"
    "Pins noirs d'Autriche": "Pin noir d'Autriche"
    "Pins taeda": "Pin à l'encens (taeda)"
    "Pins Weymouth": "Pin Weymouth"
    "Sapins pectinés": "Sapin pectiné"
    "Sapins de Vancouver": "Sapin de Vancouver"
    "Sapin du Caucase (Nordmann)": "Sapin du Caucase (Nordmann)"
    "Séquoia géant": "Séquoia géant"
    "Séquoia toujours vert": "Séquoia toujours vert"
    "Thuyas": "Thuya"
    "Tsuga hétérophylle": "Tsuga hétérophylle"
    "Cyprès": "Cyprès"
    "Crytomérias": "Crytoméria"
    "Métaséquoias": "Métaséquoia"
    "Bois secs feuillus": "Trituration feuillue"
    "Bois secs résineux": "Trituration résineuse"
    "Trituration Feuillus": "Trituration feuillue"
    "Trituration Feuillus blancs": "Trituration feuillue"
    "Trituration Feuillus durs": "Trituration feuillue"
    "Trituration Résineux": "Trituration résineuse"
    "Divers feuillus": "Divers feuillus"
    "Divers résineux": "Divers résineux"


