peuplement:
  FRF: Futaie régulière feuillue
  FIF: Futaie irrégulière feuillue
  REF: Régénération feuillue
  PLF: Plantation feuillue
  FRM: Futaie régulière mixte
  FIM: Futaie irrégulière mixte
  REM: Régénération mixte
  PLM: Plantation mixte
  FRR: Futaie régulière résineuse
  FIR: Futaie irrégulière résineuse
  RER: Régénération résineuse
  PLR: Plantation résineuse
  PEU: Peupleraie
  MFT: Mélange futaie feuillus - taillis
  MRT: Mélange futaie résineuse - taillis
  MMT: Mélange futaie mixte - taillis
  TSB: Taillis balivable
  TSN: Taillis non balivable
  REC: Recrus
  LAS: Landes
  LAH: Landes humides
  CUL: Culture à gibier
  BET: Blanc étoc / Trouée / Sol nu à reboiser
  EMP: Emprise de pare-feux
  EMR: Emprise réseau
  EMD: Emprise desserte
  EAU: Eau
  BAT: Batis
  AGR: Terre
