peuplement:
  MFT: "Mélange futaie-taillis"
  FRF: "Futaie régulière feuillue"
  FIF: "Futaie irégulière feuillue"
  FRM: "Futaie régulière mélangée"
  FIM: "Futaie irégulière mélangée"
  FRR: "Futaie régulière résineuse"
  FIR: "Futaie irégulière résineuse"
  FR: "plant/reg Plantation/Regeneration"
  TS: "Taillis"
  REC: "Recrus"
  PEU: "Peupleuraie"
  BE: "Blanc-étoc"
  L: "Landes"
  ZH: "Zone humide"
  EMP: "Emprise"