peuplement:
  MFT: "Mélange Futaie Taillis"
  FRF: "Futaie Régulière Feuillue"
  FIF: "Futaie Irrégulière Feuillue"
  FRM: "Futaie Régulière Mélangée"
  FIM: "Futaie Irrégulière Mélangée"
  FRR: "Futaie Régulière Résineuse"
  FIR: "Futaie Irrégulière Résineuse"
  REG: "Plantation Régénération"
  TSE: "Taillis"
  REC: "Recrus"
  PEU: "Peupleuraie"
  BLA: "Blanc-étoc"
  LAN: "Landes"
  ZHU: "Zone humide"
  EMP: "Emprise"