pictos:
  MAR: "Mare/Source"
  ZHU: "Zone fraiche"
  PBU: "Passage busé"
  PDD: "Place de dépôt"
  BAR: "Barière"
  POR: "Porte"
  ECH: "Echelle"
  MIR: "Mirador"
  AGR: "Agrainage"
  CAB: "Cabane"
  FEP: "Feuillu épars"
  REP: "Résineux épars"
  FES: "Feuillu sec"
  RES: "Résineux sec"
  FEC: "Feuillu chablis"
  REC: "Résineux chablis"
  FER: "Feuillu remarquable"
  RER: "Résineux remarquable"
  SIR: "Site remarquable"
  FEV: "Feuillu voisin"
  REV: "Résineux voisin"
  FRV: "Feuillu &amp; résineux voisin"
  TBI: "Taillis exploitable BI"
  TBE: "Taillis exploitable BE"
  TNE: "Taillis non exploitable"
  TRO: "Trouée"
  REG: "Régénération"
  GOU: "Gouffre"
  GRO: "Grotte"
  BLO: "Blockhaus"
  ROC: "Rocher"
  CAR: "Carrière"
  CLO: "Clocher"
  CRX: "Croix"
  PYL: "Pylone"
  EOL: "Eolienne"
  PEL: "Pylone électrique"
  FLE: "Flèche direction"
  FLA: "Flèche d'accès"
  NOM: "Toponyme"
  NOO: "Toponyme hydrographique"
  CST: "Autre CST"
  OTH: "Autre"