structure:
  output_folder:
    path: [SIG, 0_OUTPUT]
    files:
      amenagements: { filename: AMENAGEMENTS.qgz,}
      assemblage: { filename: ASSEMBLAGE.qgz,}
      enjeux_environnementaux: { filename: "ENJEUX ENVIRONNEMENTAUX.qgz",}
      geologie: { filename: GEOLOGIE.qgz,}
      peuplements: { filename: PEUPLEMENTS.qgz,}
      situation: { filename: SITUATION.qgz,}

  raster_folder:
    path: [SIG, 1_RASTER]
    files:
      mns: { filename: "MNS.tif",}
      mnt: { filename: "MNT.tif",}
      mnh: { filename: "MNH.tif", style: "MNH.qml" }
      plt: { filename: "PLT.tif",}
      plt_anc: { filename: "PLT_ANC.tif",}
      irc: { filename: "IRC.tif",}
      rgb: { filename: "RGB.tif",}
      scan25: { filename: "SCAN25.tif", style: "SCAN25.qml"}

  vector_folder:
    path: [SIG, 2_VECTOR]
    files:
      ame_polygon: { filename: AME_polygon.shp }
      batica_polygon: { filename: BATICA_polygon.shp }
      com_line: { filename: COM_line.shp, style: COMS_line.qml }
      com_point: { filename: COM_point.shp, style: COMS_point.qml }
      coms_line: { filename: COMS_line.shp, style: COMS_line.qml }
      coms_point: { filename: COMS_point.shp, style: COMS_point.qml }
      coms_polygon: { filename: COMS_polygon.shp }
      geol_polygon: { filename: GEOL_polygon.shp, style: GEOL_polygon.qml }
      infra_line: { filename: INFRA_line.shp, style: INFRA_line.qml }
      infra_point: { filename: INFRA_point.shp, style: INFRA_point.qml }
      infra_point_acces: { filename: INFRA_point.shp, style: INFRA_point_ACCES.qml }
      infra_polygon: { filename: INFRA_polygon.shp, style: INFRA_polygon.qml }
      lieudit_point: { filename: LIEUDIT_point.shp, style: LIEUDIT_point.qml }
      parca_archive_polygon: { filename: PARCA-ARCHIVE_polygon.shp }
      parca_polygon: { filename: PARCA_polygon.shp, style: PARCA_polygon.qml }
      parca_polygon_legend: { filename: PARCA_polygon.shp, style: INFRASTRUCTURE_polygon.qml }
      parca_polygon_occup: { filename: PARCA_polygon.shp, style: PARCA_polygon_OCCUP.qml }
      parcelles_polygon: { filename: PARCELLES_polygon.shp }
      pf-diag_line: { filename: PROP_line.shp, style: PF-Diag_line.qml }
      pf_line: { filename: PF_line.shp, style: PF_line.qml }
      pf_polygon: { filename: PF_polygon.shp, style: PF_polygon.qml }
      pn_polygon: { filename: PN_polygon.shp }
      prop-diag_line: { filename: PROP_line.shp, style: PROP-Diag_line.qml }
      prop_line: { filename: PROP_line.shp, style: PROP_line.qml }
      prop_point: { filename: PROP_point.shp, style: PROP_point.qml }
      prop_polygon: { filename: PROP_polygon.shp, style: PROP_polygon.qml }
      road_line: { filename: ROAD_line.shp, style: ROAD_line.qml }
      road_polygon: { filename: ROAD_polygon.shp, style: ROAD_polygon.qml }
      route_line: { filename: ROUTE_line.shp, style: ROUTE_line.qml }
      sspf-diag_polygon: { filename: SSPF_polygon.shp, style: SSPF-Diag_polygon.qml }
      sspf_polygon: { filename: SSPF_polygon.shp, style: SSPF_polygon.qml }
      sspf_polygon_plt: { filename: SSPF_polygon.shp, style: SSPF2_polygon.qml }
      sspfinv_polygon: { filename: SSPFinv_polygon.shp }
      topo_line: { filename: TOPO_line.shp, style: TOPO_line.qml }
      ua_polygon: { filename: UA_polygon.shp, style: UA_polygon.qml }
      ua_polygon_ame: { filename: UA_polygon.shp, style: UA2_polygon.qml }
      ua_polygon_occup: { filename: UA_polygon.shp, style: UA3_polygon.qml }
      ua_polygon_plt: { filename: UA_polygon.shp, style: UA2_polygon.qml }
      znieff1_polygon: { filename: ZNIEFF1_polygon.shp }

  other_folder:
    path: [SIG, 3_OTHER]
    files:
      inventaire: { filename: "inventaire.gpkg"}
      inv_qfield: { filename: "inv_qfield.zip"}
