structure:
  output_folder:
    path: [SIG, 0_OUTPUT]
    files:
      amenagements: { filename: AMENAGEMENTS.qgz, }
      assemblage: { filename: ASSEMBLAGE.qgz, }
      enjeux: { filename: "ENJEUX.qgz", }
      geologie: { filename: GEOLOGIE.qgz, }
      peuplements: { filename: PEUPLEMENTS.qgz, }
      situation: { filename: SITUATION.qgz, }
      pedology: { filename: PEDOLOGY.qgz, }

  raster_folder:
    path: [SIG, 1_RASTER]
    files:
      mns: { filename: "MNS.tif", display_name: Modèle Numérique de Surface }
      mnt: { filename: "MNT.tif", display_name: Modèle Numérique de Terrain }
      mnh: { filename: "MNH.tif", style: "MNH.qml", display_name: Modèle Numérique de Hauteur }
      plt: { filename: "PLT.tif", display_name: "Carte des Peuplements" }
      plt_anc: { filename: "PLT_ANC.tif", display_name: "Carte des Peuplements Ancienne" }
      irc: { filename: "IRC.tif", display_name: "BD ORTHO - Infra-rouge couleur" }
      rgb: { filename: "RGB.tif", display_name: "BD ORTHO - Couleur"}
      scan25: { filename: "SCAN25.tif", style: "SCAN25.qml", display_name: "Scan 25"}


  vector_folder:
    path: [SIG, 2_VECTOR]
    files:
      ame_polygon: { filename: AME_polygon.shp }
      batica_polygon: { filename: BATICA_polygon.shp }
      com_line: { filename: COM_line.shp, style: COMS_line.qml, display_name: "COM_line" }
      com_point: { filename: COM_point.shp, style: COMS_point.qml, display_name: "COM_point" }
      coms_line: { filename: COMS_line.shp, style: COMS_line.qml, display_name: "COMS_line" }
      coms_point: { filename: COMS_point.shp, style: COMS_point.qml, display_name: "COMS_point" }
      coms_polygon: { filename: COMS_polygon.shp }
      geol_polygon: { filename: GEOL_polygon.shp, style: GEOL_polygon.qml, display_name: "Géologie"}
      infra_line: { filename: INFRA_line.shp, style: INFRA_line.qml, display_name: "INFRA_line" }
      infra_point_acces: { filename: INFRA_point.shp, style: INFRA_point_ACCES.qml, display_name: "INFRA_point_ACCES" }
      infra_point: { filename: INFRA_point.shp, style: INFRA_point.qml, display_name: "INFRA_point" }
      infra_polygon: { filename: INFRA_polygon.shp, style: INFRA_polygon.qml, display_name: "INFRA_polygon" }
      lieudit_point: { filename: LIEUDIT_point.shp, style: LIEUDIT_point.qml, display_name: "LIEUDIT_point" }
      parca_archive_polygon: { filename: PARCA-ARCHIVE_polygon.shp }
      parca_polygon: { filename: PARCA_polygon.shp, style: PARCA_polygon.qml, display_name: "Parcelle cadastrale" }
      parca_polygon_legend: { filename: PARCA_polygon.shp, style: INFRASTRUCTURE_polygon.qml, display_name: "Légende" }
      parca_polygon_occup: { filename: PARCA_polygon.shp, style: PARCA_polygon_OCCUP.qml, display_name: "Parcelle cadastrale *"}
      parcelles_polygon: { filename: PARCELLES_polygon.shp }
      pf_diag_line: { filename: PROP_line.shp, style: PF-Diag_line.qml, display_name: "Limite de parcelle w" }
      pf_line: { filename: PF_line.shp, style: PF_line.qml, display_name: "Limite de parcelle forestière"}
      pf_polygon: { filename: PF_polygon.shp, style: PF_polygon.qml, display_name: "Parcelle forestière"}
      pn_polygon: { filename: PN_polygon.shp }
      prop_diag_line: { filename: PROP_line.shp, style: PROP-Diag_line.qml, display_name: "Limite de propriété w"}
      prop_line: { filename: PROP_line.shp, style: PROP_line.qml, display_name: "Limite de propriété" }
      prop_point: { filename: PROP_point.shp, style: PROP_point.qml, display_name: "Centroid de propriété" }
      prop_polygon: { filename: PROP_polygon.shp, style: PROP_polygon.qml, display_name : Propriété }
      road_line: { filename: ROAD_line.shp, style: ROAD_line.qml, display_name: "ROAD_line" }
      road_polygon: { filename: ROAD_polygon.shp, style: ROAD_polygon.qml, display_name: "ROAD_polygon"}
      route_line: { filename: ROUTE_line.shp, style: ROUTE_line.qml, display_name: "ROUTE_line" }
      route_polygon: { filename: ROUTE_polygon.shp, style: ROUTE_polygon.qml, display_name: "ROUTE_polygon"}
      route_line: { filename: ROUTE_line.shp, style: ROUTE_line.qml }
      sspf_diag_polygon: { filename: SSPF_polygon.shp, style: SSPF-Diag_polygon.qml, displaay_name: "Sous-parcelle forestière w"}
      sspf_polygon: { filename: SSPF_polygon.shp, style: SSPF_polygon.qml, display_name: "Sous-parcelle forestière"}
      sspf_polygon_plt: { filename: SSPF_polygon.shp, style: SSPF2_polygon.qml, display_name: "Peuplements (SSPF)" }
      sspfinv_polygon: { filename: SSPFinv_polygon.shp }
      topo_line: { filename: TOPO_line.shp, style: TOPO_line.qml }
      ua_polygon: { filename: UA_polygon.shp, style: UA_polygon.qml, display_name: "Unité d analyse" }
      ua_polygon_ame: { filename: UA_polygon.shp, style: UA2_polygon.qml, display_name: "Aménagements (UA)" }
      ua_polygon_occup: { filename: UA_polygon.shp, style: UA3_polygon.qml, display_name: "Occupation du sol"}
      ua_polygon_plt: { filename: UA_polygon.shp, style: UA2_polygon.qml, display_name: "Peuplements (UA)" }
      znieff1_polygon: { filename: ZNIEFF1_polygon.shp }
      placette: {filename: Placette.shp, style: Placette.qml}
      transect: {filename: Transect.shp, style: Transect.qml}
      limite: {filename: Limite.shp, style: Limite.qml}
      picto: {filename: Picto.shp, style: Picto.qml}
      gha: {filename: Gha.shp, style: Gha.qml}
      tse: {filename: Tse.shp, style: Tse.qml}
      reg: {filename: Reg.shp, style: Reg.qml}
      va_ess: {filename: Va_ess.shp, style: Va_ess.qml}
      ess: {filename: Ess.shp, style: Ess.qml}
      sondage: {filename: sondage.shp, style: sondage.qml}
      horizons: {filename: horizons.shp, style: horizons.qml}

  other_folder:
    path: [SIG, 3_OTHER]
    files:
      parcellaire: { filename: parcellaire.csv }
      inventaire: { filename: inventaire.gpkg }
      inv_qfield: { filename: inv_qfield.zip }
      diagnostic: { filename: diagnostic.gpkg }
      diag_qfield: { filename: diag_qfield.zip }
