# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\OSGeo4W\apps\qgis-ltr\python\plugins\Qsequoia2\dialogs\expertise_import\expertise_import.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExpertiseImportDialog(object):
    def setupUi(self, ExpertiseImportDialog):
        ExpertiseImportDialog.setObjectName("ExpertiseImportDialog")
        ExpertiseImportDialog.resize(362, 171)
        self.buttonBox = QtWidgets.QDialogButtonBox(ExpertiseImportDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 130, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(ExpertiseImportDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 104))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_import_files = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_import_files.setObjectName("pb_import_files")
        self.verticalLayout.addWidget(self.pb_import_files)
        self.lw_selected_files = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.lw_selected_files.setObjectName("lw_selected_files")
        self.verticalLayout.addWidget(self.lw_selected_files)

        self.retranslateUi(ExpertiseImportDialog)
        self.buttonBox.accepted.connect(ExpertiseImportDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ExpertiseImportDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ExpertiseImportDialog)

    def retranslateUi(self, ExpertiseImportDialog):
        _translate = QtCore.QCoreApplication.translate
        ExpertiseImportDialog.setWindowTitle(_translate("ExpertiseImportDialog", "Dialog"))
        self.pb_import_files.setText(_translate("ExpertiseImportDialog", "Importer des géopackages"))
