# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\OSGeo4W\apps\qgis-ltr\python\plugins\Qsequoia2\dialogs\diagnostic_import\diagnostic_import.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiagnosticImportDialog(object):
    def setupUi(self, DiagnosticImportDialog):
        DiagnosticImportDialog.setObjectName("DiagnosticImportDialog")
        DiagnosticImportDialog.resize(362, 171)
        self.buttonBox = QtWidgets.QDialogButtonBox(DiagnosticImportDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 130, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(DiagnosticImportDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 104))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_import_files = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_import_files.setObjectName("pb_import_files")
        self.verticalLayout.addWidget(self.pb_import_files)
        self.lw_selected_files = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.lw_selected_files.setObjectName("lw_selected_files")
        self.verticalLayout.addWidget(self.lw_selected_files)

        self.retranslateUi(DiagnosticImportDialog)
        self.buttonBox.accepted.connect(DiagnosticImportDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DiagnosticImportDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DiagnosticImportDialog)

    def retranslateUi(self, DiagnosticImportDialog):
        _translate = QtCore.QCoreApplication.translate
        DiagnosticImportDialog.setWindowTitle(_translate("DiagnosticImportDialog", "Dialog"))
        self.pb_import_files.setText(_translate("DiagnosticImportDialog", "Importer des géopackages"))
